include Makefile.common

# If uncommented, every map will be available.
#GODMODE = -DGODMODE

DEBUG = -g -DDEBUG_ME

CXX = g++

CXXFLAGS = -O2 -I /usr/include/xcurses `pkg-config --cflags sdl2 sdl2_mixer` -U__NOSDL__ -U__NOSOUND__ -DAP_VERSION=\"$(AP_VERSION)-dev\" $(GODMODE) $(DEBUG)

# nosdl port
#CXXFLAGS = -O2 -I/usr/include/ncursesw -D__NOSDL__ -D__NOSOUND__ -DAP_VERSION=\"$(AP_VERSION)-dev\" $(GODMODE) 


LINKFLAGS = `sdl2-config --libs sdl2 sdl2_mixer` -L/usr/lib -l pdcurses -l yaml-cpp

# nosdl port
#LINKFLAGS = -L/usr/lib -l yaml-cpp -l ncursesw

%.o: src/%.cpp
	$(CXX) -c $(CXXFLAGS) $<

dev: asciiportal-dev

asciiportal-dev: $(OBJECTS)
	$(CXX) $^ $(LINKFLAGS) -o $@

clean:
	rm -f asciiportal-dev
